"""Add translations column to translation_task

Revision ID: 0eded53daf81
Revises: 
Create Date: 2024-09-22 23:35:54.814504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0eded53daf81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_task', sa.Column('translations', sa.JSON(), nullable=True))
    op.drop_column('translation_task', 'translation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_task', sa.Column('translation', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('translation_task', 'translations')
    # ### end Alembic commands ###
